package com.exc.roadlamp.eventbus;

public enum EventEnum {
    EDIT_ORDER_SUCCESS,
    ORDER_STATUS_ID_3_TO5,
    ADD_ORDER_SUCCESS,
    ORDER_OPERATOR_SUCCESS,//工单操作成功（审核，处理等等）


    HIDE_DEVICE_MAP_PAGE_SWITCH_BTN,
    SHOW_DEVICE_MAP_PAGE_SWITCH_BTN,

    DEV_MAP_SEARCH_RESULT_LIST_CLICK,//设备地图搜索结果点击

    CENTER_CONTROL_LOOP_SWITCH,//集控回路控制
    SELECT_TAB_CLICK,//tab index=0点击
    SHOW_DEVICE_MAP_FROMLIST,//从列表切换过来
    SHOW_DEVICE_INFO_QRCODE,//二维码解析数据
    ADD_DENGGAN_SUCCESS,
    ADD_DENGJU_SUCCESS,
    ADD_PEIDIANGUI_SUCCESS,
    ADD_JIKONG_SUCCESS,
    DEVICE_ITEM_CHANGE,//设备分类切换
    CHANGE_LIGHT_SUCCESS,//灯控修改
    STRATEGY_ADD_SUCCESS,//策略添加成功
    LIGHTSTRATEGY_ADD_SUCCESS,//灯具策略添加成功
    CONTROL_BINDING_SUCCESS,//灯具绑定成功

}
